enum class Mood {
    Happy,
    Energetic,
    Calm,
    Sad,
    Romantic,
    Motivated,
    Focused,
    Chill,
    Uplifted,
    Angry,
    Anxious,
    Nostalgic,
    Playful,
    Bored,
    Confused,
    Hopeful,
    Grateful,
    Lonely,
    Adventurous,
    Sleepy,
    Satisfied,
    Tense,
    Ecstatic,
    Melancholic
}

val MOOD_COLOR = mapOf(
    Mood.Happy to "#FFD93D",
    Mood.Energetic to "#FF6B00",
    Mood.Calm to "#8EC5FC",
    Mood.Sad to "#5B5EA6",
    Mood.Romantic to "#FF4F81",
    Mood.Motivated to "#00BFA6",
    Mood.Focused to "#0066CC",
    Mood.Chill to "#A0CED9",
    Mood.Uplifted to "#FFD700",
    Mood.Angry to "#E63946",
    Mood.Anxious to "#9A8C98",
    Mood.Nostalgic to "#C39BD3",
    Mood.Playful to "#F8C471",
    Mood.Bored to "#95A5A6",
    Mood.Confused to "#F5B7B1",
    Mood.Hopeful to "#7DCEA0",
    Mood.Grateful to "#58D68D",
    Mood.Lonely to "#566573",
    Mood.Adventurous to "#F39C12",
    Mood.Sleepy to "#5D6D7E",
    Mood.Satisfied to "#82E0AA",
    Mood.Tense to "#AF7AC5",
    Mood.Ecstatic to "#FF85A1",
    Mood.Melancholic to "#34495E"
)

val MOOD_ICONS = mapOf(
    Mood.Happy to "😊",
    Mood.Energetic to "⚡",
    Mood.Calm to "🌊",
    Mood.Sad to "😢",
    Mood.Romantic to "💕",
    Mood.Motivated to "🚀",
    Mood.Focused to "🎯",
    Mood.Chill to "🧊",
    Mood.Uplifted to "🌞",
    Mood.Angry to "😡",
    Mood.Anxious to "😰",
    Mood.Nostalgic to "📻",
    Mood.Playful to "🤪",
    Mood.Bored to "😐",
    Mood.Confused to "🤔",
    Mood.Hopeful to "🌱",
    Mood.Grateful to "🙏",
    Mood.Lonely to "😔",
    Mood.Adventurous to "🧭",
    Mood.Sleepy to "😴",
    Mood.Satisfied to "😌",
    Mood.Tense to "😬",
    Mood.Ecstatic to "🤩",
    Mood.Melancholic to "🌧️"
)
